[package]
name = "epserde"
authors = ["Tommaso Fontana <tommaso.fontana.96@gmail.com>", "Sebastiano Vigna <sebastiano.vigna@unimi.it>"]
description = "ε-serde is an ε-copy (i.e., almost zero-copy) serialization/deserialization framework"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/vigna/epserde-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["serialization", "zero-copy", "mmap"]

[dependencies]
mmap-rs = { version="0.6.1", optional=true }
bitflags = {version="2.4.2", default-features=false }
xxhash-rust = {version="0.8.8", default-features=false, features=["xxh3"] }
epserde-derive = { version = "=0.3.0", optional = true }
anyhow = "1.0.79"
sealed = "0.5.0"
maligned = "0.2.1"

[features]
default = ["std", "mmap-rs", "derive"]
derive = ["epserde-derive"]
std = ["alloc"]
alloc = []
